feat(force-https): add support for force-https setting
Scalingo/terraform-provider-scalingo pull request #26
Opened 2022-02-03 15:08 UTC by sihamais

Fix #10

2022-02-03 15:29 UTC, Soulou requested changes
The create should also be updated, not only the read and update.

https://github.com/Scalingo/terraform-provider-scalingo/blob/2f0b4db7a7a8ffcb10671674e875beff366d3c3e/scalingo/resource_scalingo_app.go#L50

2022-02-03 15:32 UTC, brandon-welsch requested changes

2022-02-03 15:32 UTC, brandon-welsch commented on scalingo/resource_scalingo_app.go
> +		_, newSetting := d.GetChange("force_https")
Can you rename `newSetting` to have a better name. Something like `forceHttps` should be good

2022-02-03 15:32 UTC, brandon-welsch commented on scalingo/resource_scalingo_app.go
> +			"force_https": {
Can you add force_https to resourceAppCreate too ? Like others parameters (git_url, url) ?

Like https://github.com/Scalingo/terraform-provider-scalingo/blob/f50c52cce09fe0c3840f31b5e5d05d9ab1bbab1a/scalingo/resource_scalingo_app.go#L60

2022-02-08 14:40 UTC, sihamais commented on scalingo/resource_scalingo_app.go
> +			"force_https": {
`force_https` does not apply on the creation of an app. The API does not have a param `force_https` on creation. It will always be false.

2022-02-08 14:45 UTC, Soulou commented on scalingo/resource_scalingo_app.go
> +			"force_https": {
So can you update the method to do the creation, then set `force_https`, (It can be a create for Terraform, but create + update to the Scalingo API)

2022-02-08 14:48 UTC, sihamais commented on scalingo/resource_scalingo_app.go
> +			"force_https": {
Ok will do.

2022-02-08 14:49 UTC, brandon-welsch commented on scalingo/resource_scalingo_app.go
> +			"force_https": {
Agree with Léo, we want to todo all the actions in one terraform apply

2022-02-08 15:13 UTC, brandon-welsch approved these changes
LGTM but I would like Leo review too before it's merged

2022-02-08 15:38 UTC, Soulou commented
@sihamais I don't see the readme change here, could you add it?

2022-02-08 15:44 UTC, sihamais commented
> @sihamais I don't see the readme change here, could you add it?

It is being done in here https://github.com/Scalingo/scalingo-terraform/pull/235. and soon on a notion document. Should I duplicate it here?

2022-02-14 13:01 UTC, merged