Datasource scm integration
Scalingo/terraform-provider-scalingo pull request #67
Opened 2022-09-13 14:32 UTC by SCedricThomas

fix #55

2022-09-14 08:18 UTC, curzolapierre requested changes
Just a question, otherwise LGTM

2022-09-14 08:18 UTC, curzolapierre commented on scalingo/data_scalingo_scm_integration.go
> +			},
What is the reason to not support the `owner` field?

2022-09-14 09:42 UTC, SCedricThomas commented on scalingo/data_scalingo_scm_integration.go
> +			},
This field is not  provided by go-scalingo

2022-09-14 12:56 UTC, curzolapierre commented on scalingo/data_scalingo_scm_integration.go
> +			},
Ok so I think we should update go-scalingo first.
Could you handle it?

2022-09-14 12:58 UTC, SCedricThomas commented on scalingo/data_scalingo_scm_integration.go
> +			},
OMW

2022-09-16 07:48 UTC, curzolapierre approved these changes
LGTM

2022-09-16 13:42 UTC, curzolapierre requested changes
Small improvement following the recent Go update on this project.

2022-09-16 13:42 UTC, curzolapierre commented on scalingo/data_scalingo_scm_integration.go
> +	selectedIntegrations := filterScmIntegrations(integrations, func(element scalingo.SCMIntegration) bool {
You should use `keepIf` function now :wink:

2022-09-16 15:14 UTC, curzolapierre approved these changes

2022-09-19 07:25 UTC, merged